fix code
bearsunday/bearsunday.github.io pull request #196
Opened 2021-07-02 09:45 UTC by oishii-pudding

php8.0.0のバージョンでマニュアルを進めていましたが、
途中で動作しない箇所がありました。
(https://bearsunday.github.io/manuals/1.0/ja/tutorial.html#post%E3%83%AA%E3%82%AF%E3%82%A8%E3%82%B9%E3%83%88)

gitでbearsunday/tutorial1に記載されたコードを書くと、動作しましたので、
こちらのコードをマニュアルに記載して頂けると、チュートリアルをよりすすめやすいのではと思いました。
https://github.com/bearsunday/tutorial1/blob/v2/bin/test.php

また、現状のマニュアルではprod-cli-hal-api-appのみが記載されているため、
ここの箇所では三項演算子を使用せず、'prod-cli-hal-api-app'のみを指定しました。

PHP_SAPI === 'cli'でない場合に言及する際は
`curl`コマンドを使用する直前などに改めて追加すると
マニュアルの流れがより追いやすくなるのではと思いました。

ご確認宜しくお願いします。

2021-07-02 14:27 UTC, koriym requested changes
new Bootstrap()の前後のスペースを除去します。

2021-07-02 14:29 UTC, koriym commented
PRありがとうございます！

> 途中で動作しない箇所がありました。

詳しく教えてください。

2021-07-05 03:05 UTC, oishii-pudding commented
ご確認ありがとうございます！

bin/test.phpに次のコードを記載し、
```
bin/test.php
require dirname(__DIR__) . '/autoload.php';
exit(( require dirname(__DIR__) . '/bootstrap.php' )('prod-cli-hal-api-app'));
```
コンソールからコマンドでリクエスト（`php bin/test.php post '/todos?todo=shopping'`）した際にエラーが表示されます。


実際に発生するエラーは下記です。
vagrantを立ち上げて行っています。(codeフォルダとMyvendor.Weekdayフォルダをマウントしています)
Myvendor.Weekdayの直下にbootsrap.phpがないため、開けないというエラーになります。

```
Error
Warning: require(/home/vagrant/code/bootstrap.php): Failed to open stream: No such file or directory in /home/vagrant/code/bin/test.php on line 14
PHP Fatal error:  Uncaught Error: Failed opening required '/home/vagrant/code/bootstrap.php' (include_path='.:/usr/share/php') in /home/vagrant/code/bin/test.php:14
```

マニュアルの古いバージョンではこちらの書き方を使用しているので、
この部分のみ古いバージョンのまま置き換えされていなかったのかなと思いました。

ご確認宜しくお願いします！

2021-07-05 09:48 UTC, koriym commented
@oishii-pudding 丁寧にありがとうございました。古いマニュアルのがそのまま残ってたようです。

2021-07-05 09:48 UTC, merged