リソースの再構成
bearsunday/bearsunday.github.io pull request #214
Opened 2022-03-21 10:20 UTC by koriym

* 長すぎるので４つに分割
* ベストプラクティスをコーディングガイドからのリンクに
* 表現を簡素に校正

2022-03-24 03:16 UTC, NaokiTsuchiya requested changes

2022-03-24 03:16 UTC, NaokiTsuchiya commented on manuals/1.0/ja/resource_renderer.md
> +ResourceObjectのリクエストメソッドではリソースの表現について関心を持ちません。コンテキストに応じて注入されたレンダラーがリソースの表現を生成します。同じアプリケーションがコンテキストを変えるだけでHTMLで出力されたり、JSONで出力されて利します。
```suggestion
ResourceObjectのリクエストメソッドではリソースの表現について関心を持ちません。コンテキストに応じて注入されたレンダラーがリソースの表現を生成します。同じアプリケーションがコンテキストを変えるだけでHTMLで出力されたり、JSONで出力されたりします。
```

2022-03-24 03:16 UTC, NaokiTsuchiya commented on manuals/1.0/en/resource_link.md
> +    #Embed(rel: 'sports', src: '/news/sports')]
```suggestion
    #[Embed(rel: 'sports', src: '/news/sports')]
```

2022-03-24 03:16 UTC, NaokiTsuchiya commented on manuals/1.0/en/resource_link.md
> +    #Embed(rel: 'weather', src: '/news/weather')]
```suggestion
    #[Embed(rel: 'weather', src: '/news/weather')]
```

2022-03-24 07:32 UTC, koriym reviewed
@NaokiTsuchiya ARIGATO!

2022-03-24 23:05 UTC, NaokiTsuchiya requested changes

2022-03-25 00:34 UTC, NaokiTsuchiya approved these changes

2022-03-25 14:34 UTC, merged